# ------------------------------------------------------------
#  1. SERVER / TERMINAL
# ------------------------------------------------------------
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 10
set -g focus-events on
set -g history-limit 10000

set -g renumber-windows on
set -g set-clipboard on

set -g  window-size latest
setw -g aggressive-resize on

# ------------------------------------------------------------
#  2. PREFIX  &  INDEX
# ------------------------------------------------------------
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

set -g base-index 1
set -g pane-base-index 3

bind r source-file ~/.tmux.conf \; display-message "Config tmux reload !!!"

# ------------------------------------------------------------
#  3. SPLIT WINDOW
# ------------------------------------------------------------
unbind %
bind '|' split-window -h -c '#{pane_current_path}'

unbind '"'
bind - split-window -v -c '#{pane_current_path}'

# ------------------------------------------------------------
#  4. RESIZE PANE
# ------------------------------------------------------------
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5


# ------------------------------------------------------------
#  5. MOUSE
# ------------------------------------------------------------
bind m set -g mouse \; display-message "mouse: #{?mouse,on,off}"

# ------------------------------------------------------------
#  6. PLUGIN
# ------------------------------------------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tmux-cpu'          # need to module cpu/ram
set -g @plugin 'xamut/tmux-weather'             # provide format #{weather}
set -g @plugin 'tmux-plugins/tmux-resurrect'    # prefix+Ctrl-s save / prefix+Ctrl-r recovery
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_current_text_color   "#{@thm_surface_1}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_current_text "#[bg=#{@thm_mantle}] #{b:pane_current_path}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_number_color "#{@thm_lavender}"
 
run '~/.tmux/plugins/tpm/tpm'

set -g status-style fg=default,bg=default
set -g status-interval 15
set -g window-status-separator ""
set -g status-left-length  100
set -g status-right-length 100
 
set -g status-left "#[bg=#{@thm_green},fg=#{@thm_crust}]#[reverse]█#[noreverse]#S "

set -g  status-right ""
set -agF status-right "#{E:@catppuccin_status_cpu} "   # CPU (catppuccin-styled)
set -agF status-right "#{E:@catppuccin_status_ram} "
set -agF status-right "#{E:@catppuccin_status_date_time}"

run '~/.tmux/plugins/tmux-cpu/cpu.tmux'
# run '~/.tmux/plugins/tmux-weather/tmux-weather.tmux'

#------------------------------------------------------------
#  8. COPY / PASTE
# ------------------------------------------------------------
bind Enter copy-mode
bind b list-buffers
bind p paste-buffer
bind P choose-buffer
 
# copy-mode style VIM
setw -g mode-keys vi
bind -T copy-mode-vi v      send -X begin-selection
bind -T copy-mode-vi C-v    send -X rectangle-toggle
bind -T copy-mode-vi H      send -X start-of-line
bind -T copy-mode-vi L      send -X end-of-line
bind -T copy-mode-vi y      send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel






